### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by NikoN0777** [Bugadinho/Cork#11]
![image](https://github.com/Bugadinho/Cork/assets/71526347/ce66efec-c267-48c4-b795-f35557f023aa)

**Comment by NikoN0777** [comment]
.

**Comment by NikoN0777** [comment]
(when trying to install corky, gives this error)
![image](https://github.com/Bugadinho/Cork/assets/71526347/40ef5a41-32c8-4028-8808-b52ac12e4c71)

**Comment by Bugadinho** [comment]
> (when trying to install corky, gives this error)
> ![image](https://github.com/Bugadinho/Cork/assets/71526347/40ef5a41-32c8-4028-8808-b52ac12e4c71)
> 

Try installing the required KDE Platform first with:
`flatpak install --user org.kde.Platform/x86_64/6.5`

**Comment by NikoN0777** [comment]
> > (when trying to install corky, gives this error)
> > ![image](https://user-images.githubusercontent.com/71526347/263301661-40ef5a41-32c8-4028-8808-b52ac12e4c71.png)
> 
> Try installing the required KDE Platform first with: `flatpak install --user org.kde.Platform/x86_64/6.5`

installed the platform using `flatpak install org.kde.Platform`
and i could install it
but when im trying to install roblox player it says there is no command called cork?
![image](https://github.com/Bugadinho/Cork/assets/71526347/ddebe732-e2bf-462c-882b-7b8c7953c86c)

sorry if i cant understand, i dont know much about linux yet

**Comment by Bugadinho** [comment]
> > > (when trying to install corky, gives this error)
> > > ![image](https://user-images.githubusercontent.com/71526347/263301661-40ef5a41-32c8-4028-8808-b52ac12e4c71.png)
> > 
> > Try installing the required KDE Platform first with: `flatpak install --user org.kde.Platform/x86_64/6.5`
> 
> installed the platform using `flatpak install org.kde.Platform`
> and i could install corky
> but when im trying to install roblox player it says there is no command called cork?
> ![image](https://github.com/Bugadinho/Cork/assets/71526347/ddebe732-e2bf-462c-882b-7b8c7953c86c)
> 
> sorry if i cant understand, i dont know much about linux yet
> 

In the flatpak version, the `cork` gets replaced by `flatpak run io.github.bugadinho.Corky`, so you can use `flatpak run io.github.bugadinho.Corky install` instead.

**Comment by NikoN0777** [comment]
> > > > (when trying to install corky, gives this error)
> > > > ![image](https://user-images.githubusercontent.com/71526347/263301661-40ef5a41-32c8-4028-8808-b52ac12e4c71.png)
> > > 
> > > 
> > > Try installing the required KDE Platform first with: `flatpak install --user org.kde.Platform/x86_64/6.5`
> > 
> > 
> > installed the platform using `flatpak install org.kde.Platform`
> > and i could install corky
> > but when im trying to install roblox player it says there is no command called cork?
> > ![image](https://user-images.githubusercontent.com/71526347/263344577-ddebe732-e2bf-462c-882b-7b8c7953c86c.png)
> > sorry if i cant understand, i dont know much about linux yet
> 
> In the flatpak version, the `cork` command gets replaced by `flatpak run io.github.bugadinho.Corky`, so you can use `flatpak run io.github.bugadinho.Corky install` instead. However note that if you are following a guide, there is no need to alter the Wine version or any configuration, since the flatpak version is already pre-configured.
Oh ok. thanks alot for your help.
