### ISSUE TITLE
"Wine is not supported"

### ISSUE THREAD

**Issue by Weather-OS** [Bugadinho/Cork#4]
I'm trying to use Cork for Roblox, But everytime I launch it, it crashes with "Wine is not supported". Is there any way that I can fix this?

Wine version: wine-8.13
Linux revision: Linux archpc 6.1.45-1-lts #1 SMP PREEMPT_DYNAMIC Fri, 11 Aug 2023 11:28:00 +0000 x86_64 GNU/Linux
Distro: Arch Linux x86_64

**Comment by Kaydax** [comment]
Set your channel in the settings to `zintegration`, this will use the current dev build that allows for wine

**Comment by Weather-OS** [comment]
Yep. That fixed it, Although I had to use Proton for it.
Can't apply the mouse patch for Wayland though which is sad, So I resorted to using gamescope for now.
Thanks.
