### ISSUE TITLE
Player doesn't run

### ISSUE THREAD

**Issue by Kassiee** [Bugadinho/Cork#7]
I've followed the installation steps normally, had wine installed, and even tried Wine ge custom, but neither versions worked, I've tried using 3 different wine binaries (wine, wine-nine and wine-staging), didn't do a thing either

**Comment by Bugadinho** [comment]
That's unfortunate, could you send your settings.json file and the latest logs on `/.cache/cork/logs/` so i can try to help you?

**Comment by Kassiee** [comment]
settings.json
`{
    "cork": {
        "splash": true,
        "loglevel": "info",
        "launcher": "",
        "environment": {}
    },
    "wine": {
        "dist": "/home/kassie/Downloads/lutris-GE-Proton8-14-x86_64/",
        "type": "wine",
        "environment": {
            "WINEDLLOVERRIDES": "winemenubuilder.exe=d"
        }
    },
    "roblox": {
        "channel": "zintegration",
        "player": {
            "prelauncher": "",
            "postlauncher": "",
            "version": "",
            "environment": {},
            "remotefflags": "",
            "fflags": {}
        },
        "studio": {
            "prelauncher": "",
            "postlauncher": "",
            "version": "",
            "environment": {}
        }
    }
}`

and the log

`INFO - Cork 1.0.0 (Alcântara)
INFO - Using Wine
INFO - Player Version: version-90198e36bd254dbd
INFO - Executing Player
WARNING - wineserver: using server-side synchronization.
WARNING - wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
WARNING - 002c:fixme:winediag:LdrInitializeThunk wine-staging 8.0 is a testing version containing experimental patches.
WARNING - 002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
WARNING - 002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
WARNING - 0074:err:wineusb:DriverEntry Failed to initialize Unix library, status 0xc0000135.
WARNING - 0074:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000135
WARNING - 003c:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 126
WARNING - 0090:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
WARNING - 0090:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
WARNING - 0090:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
WARNING - 0090:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
WARNING - 00a0:err:hid:udev_bus_init UDEV monitor creation failed
WARNING - 00e8:fixme:ntdll:NtRaiseHardError c0000005 stub
WARNING - 00e8:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
WARNING - 00e8:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
WARNING - 0128:fixme:oleacc:find_class_data unhandled window class: L"#32769"
WARNING - 0128:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
WARNING - 0128:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
WARNING - 0128:fixme:uiautomation:msaa_fragment_get_FragmentRoot 00000000008F67F8, 000000000021FAC0: stub!
WARNING - 0134:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
WARNING - 0134:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
WARNING - 0134:fixme:uiautomation:msaa_fragment_get_FragmentRoot 0000000000929628, 0000000001B4FAA0: stub!
WARNING - 00e8:fixme:imm:ImeSetActiveContext himc 0000000000010068, flag 0x1 stub!
WARNING - 00f0:fixme:imm:ImeSetActiveContext himc 0000000000010026, flag 0 stub!
WARNING - 0134:fixme:oleacc:find_class_data unhandled window class: L"#32770"
WARNING - 0134:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
WARNING - 0134:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
WARNING - 0134:fixme:uiautomation:msaa_fragment_get_FragmentRoot 00000000009296A8, 0000000001B4FAA0: stub!
WARNING - 0134:fixme:oleacc:find_class_data unhandled window class: L"Static"
WARNING - 0134:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
WARNING - 0134:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
WARNING - 0134:fixme:uiautomation:msaa_fragment_get_FragmentRoot 000000000092C028, 0000000001B4F940: stub!
WARNING - 0134:fixme:oleacc:find_class_data unhandled window class: L"Button"
WARNING - 0134:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
WARNING - 0134:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
WARNING - 0134:fixme:uiautomation:msaa_fragment_get_FragmentRoot 000000000092C0A8, 0000000001B4F940: stub!
WARNING - 0134:fixme:oleacc:find_class_data unhandled window class: L"Button"
WARNING - 0134:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
WARNING - 0134:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
WARNING - 0134:fixme:uiautomation:msaa_fragment_get_FragmentRoot 0000000000929728, 0000000001B4F940: stub!
WARNING - 0134:fixme:oleacc:find_class_data unhandled window class: L"Static"
WARNING - 0134:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
WARNING - 0134:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
WARNING - 0134:fixme:uiautomation:msaa_fragment_get_FragmentRoot 00000000009297A8, 0000000001B4F940: stub!
WARNING - 0134:fixme:oleacc:find_class_data unhandled window class: L"Static"
WARNING - 0134:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
WARNING - 0134:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
WARNING - 0134:fixme:uiautomation:msaa_fragment_get_FragmentRoot 00000000008FB988, 0000000001B4FAA0: stub!
WARNING - 0134:fixme:oleacc:find_class_data unhandled window class: L"Button"
WARNING - 0134:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
WARNING - 0134:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
WARNING - 0134:fixme:uiautomation:msaa_fragment_get_FragmentRoot 00000000008FBA08, 0000000001B4FAA0: stub!
WARNING - 0134:fixme:oleacc:find_class_data unhandled window class: L"Button"
WARNING - 0134:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
WARNING - 0134:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
WARNING - 0134:fixme:uiautomation:msaa_fragment_get_FragmentRoot 000000000094A168, 0000000001B4FAA0: stub!
WARNING - 0134:fixme:oleacc:find_class_data unhandled window class: L"Static"
WARNING - 0134:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
WARNING - 0134:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
WARNING - 0134:fixme:uiautomation:msaa_fragment_get_FragmentRoot 000000000094A1E8, 0000000001B4FAA0: stub!
WARNING - 0134:fixme:oleacc:find_class_data unhandled window class: L"Button"
WARNING - 0134:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
WARNING - 0134:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
WARNING - 0134:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
WARNING - 0134:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
WARNING - 0134:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
WARNING - 0134:fixme:uiautomation:nc_provider_GetPatternProvider 000000000092F830, 10002, 0000000001B4ECA0: stub
WARNING - 0134:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 000000000092F7A0, 10002, 0000000001B4ECA0: stub
WARNING - 0134:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
WARNING - 0134:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
WARNING - 0134:fixme:uiautomation:msaa_fragment_get_FragmentRoot 000000000094A268, 0000000001B4FAA0: stub!
WARNING - 0134:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
WARNING - 0134:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
WARNING - 0134:fixme:uiautomation:msaa_fragment_get_FragmentRoot 000000000092C128, 0000000001B4FAA0: stub!
WARNING - 0144:err:seh:call_stack_handlers invalid frame 000000017005AAE3 (0000000009A72000-0000000009C70000)
WARNING - 0144:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.
INFO - End
`

**Comment by Bugadinho** [comment]
The culprit might be the instability of the `zintegration` channel, try to switch it to `zcanary` to see if it works.

**Comment by Kassiee** [comment]
It did seem to go past the Initial process with Zintegration but didn't launch, but I still get the same error popup: "The application has encountered an unrecoverable error", and some other error that says the program has stopped and a memory dump has been added into my clipboard (that doesn't work) 

here's another log if it shows anything relevant

INFO - Cork 1.0.0 (Alcântara)
INFO - Using Wine
INFO - Player Version: version-2d6da672399b4cd0
INFO - Executing Player
WARNING - 002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
WARNING - 0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
WARNING - 0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
WARNING - 0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
WARNING - 0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
WARNING - 0144:err:winediag:gnutls_process_attach failed to load libgnutls, no support for encryption
WARNING - 0144:err:winediag:process_attach failed to load libgnutls, no support for pfx import/export
WARNING - wine: configuration in L"/home/kassie/.local/share/cork/pfx" has been updated.
WARNING - 0024:fixme:ntdll:NtRaiseHardError c0000005 stub
WARNING - 0024:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
WARNING - 0024:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
WARNING - 0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
INFO - End

**Comment by Bugadinho** [comment]
That's a little weird, what is your system configuration?

**Comment by Kassiee** [comment]
I don't kno what that means exactly, but I'm using Arch Linux with XanMod kernel on Sway (Wayland window manager)

**Comment by Bugadinho** [comment]
Perhaps try installing DXVK into Cork's prefix, that helped me sort out a similar issue with Studio.

**Comment by Kassiee** [comment]
tried it again with a regular wine binary and custom wine ge after installing dxvk onto the prefix, tried completely erasing the prefix and reinstalling everything again, didn't work, it's almost always ending with a "Segmentation fault (core dumped)" error
